apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: web
          image: gcr.io/lab6-id/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: STORAGE_SVC
              value: "storage"
          livenessProbe:
            httpGet:
              path: /phrase
              port: 3000
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    app: 
  ports:
    - protocol: 
      port: 80
      targetPort: 
  type: